server:
  port: 9999

spring:
  mvc:
    pathmatch:
       matching-strategy: ANT_PATH_MATCHER
      #Springfox使用的路径匹配是基于AntPathMatcher的，
      #而SpringBoot 2.6.X使用的是PathPatternMatcher。
      #所有得修改配置

  servlet:
    multipart:
      max-file-size: 10485760 #限制单个文件或者总上传大小，单位为 bit
      max-request-size: 10485760
      resolve-lazily: true #让报错转给手动判断处理

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wowcheat?serverTimezone=Asia/Shanghai&&useSSL=false
    username: root
    password: 123456
  #邮箱配置
  mail:
    host: smtp.qq.com  #邮箱服务器
    username:    #邮箱登录名
    password:    #三方邮箱的授权码，非登录密码
    default-encoding: utf-8  #设置默认编码类型

mybatis:
  type-aliases-package: com.cinle.wowcheat.Model
  mapper-locations: classpath:Mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true  #开启映射下划线字段
    lazy-loading-enabled: true
    aggressive-lazy-loading: false



#Swagger 配置 访问地址：swagger-ui.html 或 swagger-ui/index.html
swagger:
  enable: true


logging:
  level:
    com:
      cinle:
        wowcheat:
          Dao: debug
